### ISSUE TITLE
Keyword model refactor

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#74]
- [x] interface design for keyword match to support capacity of Chinese, Japanese, Korean...
  - [ ] options for match method enable/disable.
  - [x] cache generate/storage for each language
  - [x] https://github.com/toolgood/ToolGood.Words.Pinyin Replace PinYin.Net

Split from #26

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/111136094-50bd6c00-85b8-11eb-9a61-0693127b2c59.png)

Now we can offering multiple keyword matchers for launcher.
