### ISSUE TITLE
Error info markup improvement

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#87]
Markdown style should be improved for better readability. 

1. [x] Environment as table
2. [x] Recent log as code 
    1. [x] Remove HTML from recent log

<details><summary>Here is how it looks with above mentioned changes.</summary>

## Environment

|   Component   |                      Version                      |
| :-------------- | :------------------------------------------------- |
| PRemoteM | `0.5.9.2102191952`                                |
| .NET Framework | `.NET Framework 4.8`                              |
| CLR            | `4.0.30319.42000`                                 |
| OS             | `Windows 10 Enterprise 64-bits 6.2.9200.0 (2009)` |

## Error Info
【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 > 生成 > 目标平台：x86 | x64

## Stack Trace

```
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   at FreeSql.Sqlite.SqliteCodeFirst.GetComparisonDDLStatements(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure[TEntity]()
   at PRM.Core.DB.freesql.FreeSqlDb.InitTables()
   at PRM.Core.DB.freesql.FreeSqlDb.OpenConnection(Nullable`1 type, String newConnectionString)
   at PRM.Core.Model.PrmContext.InitSqliteDb(String sqlitePath)
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

## Recent Log 

```
2021-02-19T09:45:48.2804169+01:00[ThreadId:0000000001]		Debug		Resolution Change: System.EventArgs
2021-02-19T12:27:56.3106651+01:00[ThreadId:0000000001]		Debug		Call shortcut to invoke quick window.
2021-02-19T15:28:00.7130189+01:00[ThreadId:0000000001]		Debug		Call shortcut to invoke quick window.
2021-02-19T16:46:20.7001905+01:00[ThreadId:0000000001]		<u>**<font color=Red>Fatal**</u>		System.Exception: 【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 > 生成 > 目标平台：x86 | x64 ---> System.Exception: 【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 > 生成 > 目标平台：x86 | x64
   at FreeSql.Internal.ObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)
   at FreeSql.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   --- End of inner exception stack trace ---
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   at FreeSql.Sqlite.SqliteCodeFirst.GetComparisonDDLStatements(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure[TEntity]()
   at PRM.Core.DB.freesql.FreeSqlDb.InitTables()
   at PRM.Core.DB.freesql.FreeSqlDb.OpenConnection(Nullable`1 type, String newConnectionString)
   at PRM.Core.Model.PrmContext.InitSqliteDb(String sqlitePath)
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   at FreeSql.Sqlite.SqliteCodeFirst.GetComparisonDDLStatements(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure[TEntity]()
   at PRM.Core.DB.freesql.FreeSqlDb.InitTables()
   at PRM.Core.DB.freesql.FreeSqlDb.OpenConnection(Nullable`1 type, String newConnectionString)
   at PRM.Core.Model.PrmContext.InitSqliteDb(String sqlitePath)
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2021-02-19T16:52:11.6959509+01:00[ThreadId:0000000001]		<u>**<font color=Red>Fatal**</u>		System.Exception: 【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 > 生成 > 目标平台：x86 | x64 ---> System.Exception: 【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 > 生成 > 目标平台：x86 | x64
   at FreeSql.Internal.ObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)
   at FreeSql.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   --- End of inner exception stack trace ---
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   at FreeSql.Sqlite.SqliteCodeFirst.GetComparisonDDLStatements(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure[TEntity]()
   at PRM.Core.DB.freesql.FreeSqlDb.InitTables()
   at PRM.Core.DB.freesql.FreeSqlDb.OpenConnection(Nullable`1 type, String newConnectionString)
   at PRM.Core.Model.PrmContext.InitSqliteDb(String sqlitePath)
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalar(CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   at FreeSql.Sqlite.SqliteCodeFirst.GetComparisonDDLStatements(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure[TEntity]()
   at PRM.Core.DB.freesql.FreeSqlDb.InitTables()
   at PRM.Core.DB.freesql.FreeSqlDb.OpenConnection(Nullable`1 type, String newConnectionString)
   at PRM.Core.Model.PrmContext.InitSqliteDb(String sqlitePath)
   at PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

</details>

**Comment by VShawn** [comment]
Done, here is how it looks like

<details>

## Environment

|     Component   |                       Version                      |
|:------------------|:--------------------------------------|
|PRemoteM_Debug | `0.5.10-alpha`|
|platform       | `EXE release`         |
|.NET Framework | `.NET Framework 4.8`    |
|OS             | `Windows 10 Enterprise 64-bits 6.2.9200.0 (2004)`                  |
|CLR            | `4.0.30319.42000`       |

## Error Info

test

## Stack Trace

```
   在 PRM.App.InitSystemConfig(String appDateFolder) 位置 D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:行号 156
   在 PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent) 位置 D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:行号 228
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

## Recent Log 

```
2021-02-24T18:37:52.7523419+08:00[ThreadId:0000000001]		**Fatal**		System.Exception: test
   在 PRM.App.InitSystemConfig(String appDateFolder) 位置 D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:行号 156
   在 PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent) 位置 D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:行号 228
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 PRM.App.InitSystemConfig(String appDateFolder) 位置 D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:行号 156
   在 PRM.App.App_OnStartup(Object sender, StartupEventArgs startupEvent) 位置 D:\DemoProject\PRemoteM\PRemoteM\App.xaml.cs:行号 228
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

</details>
